name: Terraform and Ansible Workflow

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Apply
      run: |
        terraform init
        terraform apply -auto-approve

    - name: Set up Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i instance.ini your-playbook.yml
